// 食品データベース (100gあたりのカロリー・マクロ栄養素)
// { name, cal, carb, protein, fat, unit }
const FOOD_DB = [
  // 主食
  { name: 'ご飯（白米）',        cal: 168, carb: 37.1, protein: 2.5, fat: 0.3, unit: 'g' },
  { name: 'ご飯（玄米）',        cal: 165, carb: 35.6, protein: 2.8, fat: 1.0, unit: 'g' },
  { name: '食パン',              cal: 264, carb: 49.0, protein: 9.3, fat: 4.4, unit: 'g' },
  { name: 'フランスパン',        cal: 279, carb: 57.5, protein: 9.4, fat: 1.3, unit: 'g' },
  { name: 'うどん（茹で）',      cal: 105, carb: 21.6, protein: 2.6, fat: 0.4, unit: 'g' },
  { name: 'そば（茹で）',        cal: 132, carb: 26.0, protein: 4.8, fat: 1.0, unit: 'g' },
  { name: 'スパゲティ（茹で）',  cal: 165, carb: 32.2, protein: 5.8, fat: 0.9, unit: 'g' },
  { name: 'ラーメン（中華麺）',  cal: 149, carb: 29.2, protein: 5.3, fat: 0.6, unit: 'g' },
  { name: 'もち',                cal: 235, carb: 50.8, protein: 4.1, fat: 0.6, unit: 'g' },
  { name: 'じゃがいも',          cal: 76,  carb: 17.3, protein: 1.8, fat: 0.1, unit: 'g' },
  { name: 'さつまいも',          cal: 126, carb: 30.3, protein: 1.2, fat: 0.2, unit: 'g' },
  { name: 'コーンフレーク',      cal: 381, carb: 83.6, protein: 7.8, fat: 1.7, unit: 'g' },
  // 肉類
  { name: '鶏胸肉（皮なし）',    cal: 116, carb: 0.0,  protein: 24.4, fat: 1.9, unit: 'g' },
  { name: '鶏もも肉（皮なし）',  cal: 138, carb: 0.0,  protein: 22.0, fat: 5.0, unit: 'g' },
  { name: '鶏ささみ',            cal: 98,  carb: 0.0,  protein: 23.0, fat: 0.8, unit: 'g' },
  { name: '豚ロース',            cal: 263, carb: 0.1,  protein: 19.3, fat: 19.2, unit: 'g' },
  { name: '豚バラ',              cal: 395, carb: 0.1,  protein: 14.4, fat: 35.4, unit: 'g' },
  { name: '豚ヒレ',             cal: 130, carb: 0.3,  protein: 22.2, fat: 3.7, unit: 'g' },
  { name: '牛ロース（脂身なし）',cal: 240, carb: 0.1,  protein: 19.0, fat: 17.4, unit: 'g' },
  { name: '牛ひき肉',            cal: 272, carb: 0.3,  protein: 17.1, fat: 21.1, unit: 'g' },
  { name: 'ベーコン',            cal: 405, carb: 0.3,  protein: 16.8, fat: 39.1, unit: 'g' },
  { name: 'ウインナー',          cal: 321, carb: 3.3,  protein: 11.5, fat: 28.5, unit: 'g' },
  { name: 'サラミ',              cal: 497, carb: 1.8,  protein: 22.6, fat: 43.0, unit: 'g' },
  // 魚介類
  { name: '鮭（さけ）',          cal: 139, carb: 0.1,  protein: 22.3, fat: 4.1, unit: 'g' },
  { name: 'まぐろ（赤身）',      cal: 125, carb: 0.1,  protein: 26.4, fat: 1.4, unit: 'g' },
  { name: 'まぐろ（トロ）',      cal: 344, carb: 0.1,  protein: 20.1, fat: 27.5, unit: 'g' },
  { name: 'さんま',              cal: 318, carb: 0.1,  protein: 18.1, fat: 25.6, unit: 'g' },
  { name: 'あじ',                cal: 126, carb: 0.1,  protein: 20.7, fat: 4.5, unit: 'g' },
  { name: 'えび（むきえび）',    cal: 97,  carb: 0.1,  protein: 21.7, fat: 0.6, unit: 'g' },
  { name: 'たこ（生）',          cal: 76,  carb: 0.1,  protein: 16.4, fat: 0.7, unit: 'g' },
  { name: 'いか（生）',          cal: 83,  carb: 0.1,  protein: 17.9, fat: 0.8, unit: 'g' },
  { name: 'ツナ缶（水煮）',      cal: 71,  carb: 0.1,  protein: 16.0, fat: 0.7, unit: 'g' },
  // 卵・乳製品
  { name: '卵（全卵）',          cal: 151, carb: 0.3,  protein: 12.3, fat: 10.3, unit: 'g' },
  { name: '牛乳',                cal: 67,  carb: 4.8,  protein: 3.3,  fat: 3.8, unit: 'ml' },
  { name: '豆乳（無調整）',      cal: 46,  carb: 2.9,  protein: 3.6,  fat: 2.0, unit: 'ml' },
  { name: 'プレーンヨーグルト',  cal: 62,  carb: 4.9,  protein: 3.6,  fat: 3.0, unit: 'g' },
  { name: 'チーズ（プロセス）',  cal: 339, carb: 1.3,  protein: 22.7, fat: 26.0, unit: 'g' },
  { name: 'バター',              cal: 745, carb: 0.2,  protein: 0.5,  fat: 83.0, unit: 'g' },
  // 野菜
  { name: 'キャベツ',            cal: 23,  carb: 5.2,  protein: 1.3,  fat: 0.2, unit: 'g' },
  { name: 'レタス',              cal: 12,  carb: 1.7,  protein: 0.6,  fat: 0.1, unit: 'g' },
  { name: 'トマト',              cal: 19,  carb: 3.7,  protein: 0.7,  fat: 0.1, unit: 'g' },
  { name: 'きゅうり',            cal: 14,  carb: 3.0,  protein: 1.0,  fat: 0.1, unit: 'g' },
  { name: 'にんじん',            cal: 39,  carb: 9.3,  protein: 0.7,  fat: 0.1, unit: 'g' },
  { name: 'たまねぎ',            cal: 37,  carb: 8.9,  protein: 1.0,  fat: 0.1, unit: 'g' },
  { name: 'ほうれん草',          cal: 20,  carb: 3.1,  protein: 2.2,  fat: 0.4, unit: 'g' },
  { name: 'ブロッコリー',        cal: 33,  carb: 5.2,  protein: 4.3,  fat: 0.5, unit: 'g' },
  { name: 'なす',                cal: 22,  carb: 5.1,  protein: 1.1,  fat: 0.1, unit: 'g' },
  { name: 'ピーマン',            cal: 22,  carb: 5.1,  protein: 0.9,  fat: 0.2, unit: 'g' },
  { name: 'もやし',              cal: 15,  carb: 2.6,  protein: 1.7,  fat: 0.1, unit: 'g' },
  { name: '豆腐（木綿）',        cal: 72,  carb: 1.5,  protein: 7.0,  fat: 4.2, unit: 'g' },
  { name: '豆腐（絹ごし）',      cal: 56,  carb: 2.0,  protein: 5.3,  fat: 3.0, unit: 'g' },
  { name: '納豆',                cal: 200, carb: 12.1, protein: 16.5, fat: 10.0, unit: 'g' },
  // 果物
  { name: 'りんご',              cal: 61,  carb: 16.2, protein: 0.2,  fat: 0.2, unit: 'g' },
  { name: 'バナナ',              cal: 86,  carb: 22.5, protein: 1.1,  fat: 0.2, unit: 'g' },
  { name: 'みかん',              cal: 46,  carb: 11.0, protein: 0.7,  fat: 0.1, unit: 'g' },
  { name: 'いちご',              cal: 34,  carb: 8.5,  protein: 0.9,  fat: 0.1, unit: 'g' },
  { name: 'ぶどう',              cal: 59,  carb: 15.7, protein: 0.4,  fat: 0.1, unit: 'g' },
  { name: 'オレンジ',            cal: 46,  carb: 11.8, protein: 0.9,  fat: 0.1, unit: 'g' },
  { name: 'アボカド',            cal: 187, carb: 7.9,  protein: 2.5,  fat: 18.7, unit: 'g' },
  // 飲み物
  { name: 'コーラ',              cal: 45,  carb: 11.4, protein: 0.0,  fat: 0.0, unit: 'ml' },
  { name: 'オレンジジュース',    cal: 42,  carb: 10.3, protein: 0.6,  fat: 0.1, unit: 'ml' },
  { name: 'ビール',              cal: 40,  carb: 3.1,  protein: 0.3,  fat: 0.0, unit: 'ml' },
  { name: '日本酒',              cal: 109, carb: 5.0,  protein: 0.5,  fat: 0.0, unit: 'ml' },
  { name: 'ワイン（赤）',        cal: 73,  carb: 1.5,  protein: 0.2,  fat: 0.0, unit: 'ml' },
  { name: '緑茶',                cal: 2,   carb: 0.3,  protein: 0.2,  fat: 0.0, unit: 'ml' },
  { name: 'コーヒー（ブラック）',cal: 4,   carb: 0.7,  protein: 0.2,  fat: 0.0, unit: 'ml' },
  // スナック・お菓子
  { name: 'ポテトチップス',      cal: 554, carb: 54.7, protein: 4.7,  fat: 35.2, unit: 'g' },
  { name: 'チョコレート',        cal: 558, carb: 55.8, protein: 6.9,  fat: 34.1, unit: 'g' },
  { name: 'アイスクリーム',      cal: 212, carb: 23.9, protein: 3.4,  fat: 12.0, unit: 'g' },
  { name: 'クッキー',            cal: 486, carb: 68.5, protein: 6.5,  fat: 22.0, unit: 'g' },
  { name: 'どら焼き',            cal: 284, carb: 58.0, protein: 6.5,  fat: 3.2, unit: 'g' },
  { name: 'ショートケーキ',      cal: 344, carb: 42.0, protein: 6.5,  fat: 16.5, unit: 'g' },
];

// 運動データベース (MET値)
// 消費カロリー = MET × 体重(kg) × 時間(h)
const EXERCISE_DB = [
  { name: 'ウォーキング（普通）',    met: 3.5,  icon: '🚶' },
  { name: 'ウォーキング（速歩）',    met: 4.5,  icon: '🚶' },
  { name: 'ジョギング',              met: 7.0,  icon: '🏃' },
  { name: 'ランニング（8km/h）',     met: 8.0,  icon: '🏃' },
  { name: 'ランニング（10km/h）',    met: 10.0, icon: '🏃' },
  { name: 'マラソン',               met: 13.3, icon: '🏃' },
  { name: '自転車（普通）',          met: 4.0,  icon: '🚴' },
  { name: '自転車（速い）',          met: 8.0,  icon: '🚴' },
  { name: '水泳（クロール・ゆっくり）', met: 5.8, icon: '🏊' },
  { name: '水泳（クロール・速い）',  met: 9.8,  icon: '🏊' },
  { name: '水泳（平泳ぎ）',          met: 5.3,  icon: '🏊' },
  { name: '筋トレ（軽い）',          met: 3.5,  icon: '💪' },
  { name: '筋トレ（中程度）',        met: 5.0,  icon: '💪' },
  { name: '筋トレ（高強度）',        met: 8.0,  icon: '💪' },
  { name: 'スクワット',              met: 5.0,  icon: '💪' },
  { name: 'プランク',                met: 4.0,  icon: '💪' },
  { name: 'ヨガ',                    met: 2.5,  icon: '🧘' },
  { name: 'ストレッチ',              met: 2.3,  icon: '🧘' },
  { name: 'ピラティス',              met: 3.0,  icon: '🧘' },
  { name: 'バドミントン',            met: 5.5,  icon: '🏸' },
  { name: 'テニス（シングルス）',    met: 8.0,  icon: '🎾' },
  { name: 'バスケットボール',        met: 6.5,  icon: '🏀' },
  { name: 'サッカー',                met: 7.0,  icon: '⚽' },
  { name: '野球',                    met: 5.0,  icon: '⚾' },
  { name: '縄跳び',                  met: 10.0, icon: '🤸' },
  { name: 'エアロビクス',            met: 6.0,  icon: '💃' },
  { name: 'ダンス',                  met: 4.8,  icon: '💃' },
  { name: '階段昇降',                met: 4.0,  icon: '🪜' },
  { name: '掃除（普通）',            met: 3.5,  icon: '🧹' },
  { name: '買い物（歩き）',          met: 2.3,  icon: '🛍️' },
];
